image: gitlab/dind

# Use the OverlayFS driver for improved performance.
variables:
  DOCKER_DRIVER: overlay

services:
  - docker:dind

stages:
  - build
  - tests
  #- deploy_prod

before_script:
  - docker info


before_script:
  - docker login -u $CI_REGISTRY_USER -p $CI_REGISTRY_PASSWORD $CI_REGISTRY

#build:
#  stage: build
#  script:
#    - 'cp env.orig .env'
#    - './run.sh docker buildtest'


test:
  stage: tests

  script:
    - 'cp env.test.orig .env'
    - './run.sh stack'
    - './run.sh test style'
#  only:
#   - merge_requests

#deploy_run_sh:
#  stage: deploy_prod
#  script: './run.sh stack'
