image: docker

variables:
  DOCKER_DRIVER: overlay

services:
  - docker:dind

cache:
  key: coolkey

stages:
  - tests
  - deploy

before_script:
  - docker info
  - docker login -u $CI_REGISTRY_USER -p $CI_REGISTRY_PASSWORD $CI_REGISTRY
  - apk add --no-cache docker-compose bash
  - eval $(ssh-agent -s)
  - echo "$SSH_PRIVATE_KEY" | tr -d '\r' | ssh-add -
  - mkdir -p ~/.ssh
  - chmod 700 ~/.ssh
  - echo "$SSH_KNOWN_HOSTS" > ~/.ssh/known_hosts
  - chmod 644 ~/.ssh/known_hosts

test:
  stage: tests
  when: manual
  only:
    - merge_requests
  script:
    - 'ls'
    - 'cp env.test.orig .env'
    - './run.sh stack'
    - './run.sh test style'
    - './run.sh test unit'

#build_package:
#  stage: post_tests
#  script:
#    - 'docker login -u gitlab-ci-token -p $CI_JOB_TOKEN $CI_REGISTRY'
#    - 'docker build -t $CI_REGISTRY/sm_backend -f build/virtualenv/Dockerfile build/virtualenv'
#    - 'docker push $CI_REGISTRY/sm_backend'

deploy_prod:
  stage: deploy
  script:
    - ssh root@sudmonster.ovdinfo.org "cd /home/oi-sud-monster-frontend && git checkout . && git pull origin master && cd ../oi-sud-monster && docker-compose stop celery_main && docker-compose stop celery_other && docker-compose stop celery_grouper && git checkout . && git pull origin master && ./run.sh stack && exit"
  when: manual
  only:
    - merge_requests
