version: '3.4'

x-global-environment: &global-environment
  C_PROJECT_VERSION: 429e9fff5827e7aa68d79300906dbc556394149d
  C_PROJECT_STACK: dev

x-projectname: &oi_sud
    env_file: .env
    image: oi-sud-monster-virtualenv-test:latest
    environment:
        <<: *global-environment
    volumes:
        - ./:/code
    restart: on-failure

services:
    db:
      image: postgres:alpine
      ports:
      - 5432
      restart: always
      environment:
        POSTGRES_USER: "sudmonster"
        POSTGRES_PASSWORD: "sudmonster"
        POSTGRES_DB: "sudmonster"
      volumes:
        - db-data:/data/db
        - ./share/sql:/docker-entrypoint-initdb.d

    redis:
        image: redis:4.0.11
        volumes:
            - ./.docker/redis/data:/var/redis
        restart: always

    backend:
        <<: *oi_sud
        environment:
          DJANGO_MANAGE_MIGRATE: "on"
          DJANGO_MANAGE_COLLECTSTATIC: "on"
        volumes:
          - ./:/code
          - ./.docker/static:/var/www/static
          - ./.docker/media:/var/www/media
        command: ["gunicorn", "oi_sud.wsgi:application", "-b", "0.0.0.0:8081", "--name", "oi_sud", "--reload"]
        ports:
          - "8082:8081"

    test:
        <<: *oi_sud
        environment:
          DJANGO_SETTINGS_MODULE: 'oi_sud.config.test'
        command: ["echo", "'test'"]

    celery_main:
        <<: *oi_sud
        command: ["celery", "-A", "oi_sud", "worker", "-l", "info", "-Q", "main", "-c", "1", "-n", "main" ]

    celery_other:
        <<: *oi_sud
        command: ["celery", "-A", "oi_sud", "worker", "-l", "info", "-Q", "other", "-c", "8", "-n", "other" ]

    celerybeat:
        <<: *oi_sud
        command: ["celery", "-A", "oi_sud", "beat", "--scheduler", "django_celery_beat.schedulers:DatabaseScheduler", "-l", "info", "--pidfile", "/tmp/celerybeat1234.pid", "--schedule", "/tmp/celerybeat-schedule"]

    flower:
      image: mher/flower
      command: ["flower", "--broker=redis://redis:6379/0", "--port=8888"]
      ports:
         - 8888:8888
volumes:
  db-data: