version: '3.6'

x-global-environment: &global-environment
  C_PROJECT_VERSION: 4b7fd68241e338367703016880df6861f8dc6569
  C_PROJECT_STACK: prod
  C_PROJECT_NAME: python-project
  C_PROJECT_REGISTRY: default

networks:
  backend:
    external: true

services:
  projectname: &projectname-base
    env_file: .env
    expose:
      - 8000
    image: "default/python-project:4b7fd68241e338367703016880df6861f8dc6569"
    command: ["gunicorn", "projectname.app:app", "-b", "0.0.0.0:8000", "--name", "iprojectname", "--reload"]
    environment:
        <<: *global-environment
    labels:
      - "traefik.enable=true"
      - "traefik.backend=projectname"
      - "traefik.frontend.entryPoints=http"
      - "traefik.frontend.rule=HostRegexp:{subdomain:^projectname.*}.stage.local,{subdomain:^projectname.*}.prod.local;PathPrefix:/stat"
      - "traefik.docker.network=backend"
      - "traefik.port=8000"
    restart: unless-stopped
    networks:
      - backend
