version: '3.4'

x-global-environment: &global-environment
  C_PROJECT_VERSION: 820a4a25df093594df7a2687ce4bec2f92f64ba7
  C_PROJECT_STACK: dev

x-projectname: &oi_sud
    env_file: .env
    image: oi_sud_monster-virtualenv-test:latest
    environment:
        <<: *global-environment
    volumes:
        - ./:/code
    restart: on-failure

services:
    db:
      image: postgres:alpine
      ports:
      - 5432
      restart: always
      environment:
        POSTGRES_USER: "sudmonster"
        POSTGRES_PASSWORD: "sudmonster"
        POSTGRES_DB: "sudmonster"
      volumes:
        - db-data:/data/db
        - ./share/sql:/docker-entrypoint-initdb.d

    redis:
        image: redis:4.0.11
        volumes:
            - ./.docker/redis/data:/var/redis
        restart: always

    backend:
        <<: *oi_sud
        environment:
          DJANGO_MANAGE_MIGRATE: "on"
          DJANGO_MANAGE_COLLECTSTATIC: "on"
        volumes:
          - ./:/code
          - ./.docker/static:/var/www/static
          - ./.docker/media:/var/www/media
        command: ["gunicorn", "oi_sud.wsgi:application", "-b", "0.0.0.0:8081", "--name", "oi_sud", "--reload"]
        ports:
          - "8081:8081"

    test:
        <<: *oi_sud
        environment:
          DJANGO_SETTINGS_MODULE: 'oi_sud.config.test'
        command: ["echo", "'test'"]

volumes:
  db-data: