# Generated by Django 2.2 on 2019-04-17 08:13

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='CodexArticle',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('article_number', models.CharField(max_length=10, verbose_name='Номер cтатьи')),
                ('part', models.CharField(blank=True, max_length=10, null=True, verbose_name='Часть статьи')),
                ('short_title', models.TextField(blank=True, null=True, verbose_name='Короткое описание')),
                ('parent_title', models.TextField(blank=True, null=True, verbose_name='Родительская статья')),
                ('full_text', models.TextField(blank=True, null=True, verbose_name='Текст статьи')),
                ('codex', models.CharField(choices=[('uk', 'УК'), ('koap', 'КОАП')], max_length=4, verbose_name='Кодекс')),
            ],
            options={
                'verbose_name': 'Статья',
                'verbose_name_plural': 'Статьи',
            },
        ),
    ]
