# Generated by Django 2.1.7 on 2019-04-01 19:27

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='CodexArticle',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('article_number', models.CharField(max_length=10)),
                ('part', models.CharField(max_length=10)),
                ('short_title', models.TextField(blank=True, null=True)),
                ('parent_title', models.TextField(blank=True, null=True)),
                ('full_text', models.TextField(blank=True, null=True)),
                ('codex', models.CharField(choices=[('uk', 'УК'), ('koap', 'КОАП')], max_length=4)),
            ],
        ),
    ]
