# Generated by Django 2.2.6 on 2019-10-04 17:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('codex', '0002_koapcodexarticle_ukcodexarticle'),
    ]

    operations = [
        migrations.AddField(
            model_name='codexarticle',
            name='active',
            field=models.BooleanField(default=True, verbose_name='Дела по статье собираются'),
        ),
    ]
