# Generated by Django 2.1.7 on 2019-04-03 12:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('codex', '0002_auto_20190401_2044'),
    ]

    operations = [
        migrations.AddField(
            model_name='codexarticle',
            name='m_judge',
            field=models.BooleanField(default=False),
        ),
    ]
