# Generated by Django 2.2.8 on 2020-01-21 16:27

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('cases', '0022_auto_20200121_1627'),
        ('users', '0002_auto_20191030_1029'),
    ]

    operations = [
        migrations.AddField(
            model_name='customuser',
            name='favorite_cases',
            field=models.ManyToManyField(blank=True, related_name='favorited_users', to='cases.Case'),
        ),
        migrations.CreateModel(
            name='UserTag',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('cases', models.ManyToManyField(blank=True, related_name='user_tags', to='cases.Case')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='tags', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
