# Generated by Django 2.2.8 on 2020-01-22 18:19

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0002_auto_20191107_0807'),
        ('users', '0003_auto_20200121_1627'),
    ]

    operations = [
    ]
