# Generated by Django 2.2.8 on 2020-08-25 18:23

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0004_auto_20200623_2111'),
        ('users', '0004_merge_20200122_1819'),
    ]

    operations = [
    ]
