# Generated by Django 2.2 on 2019-04-20 07:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('courts', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='court',
            name='title',
            field=models.CharField(db_index=True, max_length=100, verbose_name='Название'),
        ),
        migrations.AlterField(
            model_name='judge',
            name='name',
            field=models.CharField(db_index=True, max_length=50),
        ),
    ]
