# Generated by Django 2.2.4 on 2019-09-02 12:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('courts', '0002_auto_20190420_0750'),
    ]

    operations = [
        migrations.AddField(
            model_name='court',
            name='not_available',
            field=models.BooleanField(default=False),
        ),
    ]
