# Generated by Django 2.1.7 on 2019-04-02 02:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('courts', '0002_auto_20190327_1302'),
    ]

    operations = [
        migrations.AlterField(
            model_name='court',
            name='site_type',
            field=models.IntegerField(choices=[(1, 'Первый тип сайта'), (2, 'Второй тип сайта'), (3, 'Московский тип сайта')], default=1),
        ),
    ]
