# Generated by Django 2.2.7 on 2019-12-05 17:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('courts', '0005_court_unprocessed_cases_urls'),
    ]

    operations = [
        migrations.AlterField(
            model_name='court',
            name='site_type',
            field=models.IntegerField(choices=[(1, 'Первый тип сайта'), (2, 'Второй тип сайта'), (3, 'Московский тип сайта'), (4, 'Мировой суд - тип msudrf')], default=1, verbose_name='Тип сайта суда'),
        ),
        migrations.AlterField(
            model_name='court',
            name='type',
            field=models.IntegerField(choices=[(0, 'Районный суд'), (1, 'Городской суд'), (2, 'Городской суд (федерального значения)'), (3, 'Областной суд'), (4, 'Краевой суд'), (5, 'Гарнизонный военный суд'), (6, 'Окружной военный (флотский) суд'), (7, 'Суд автономного округа'), (8, 'Суд автономной области'), (9, 'Участок мирового судьи')], verbose_name='Тип суда'),
        ),
    ]
