# Generated by Django 2.2 on 2019-04-17 08:13

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('codex', '0001_initial'),
        ('courts', '__first__'),
    ]

    operations = [
        migrations.CreateModel(
            name='Advocate',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'verbose_name': 'Адвокат',
                'verbose_name_plural': 'Адвокаты',
            },
        ),
        migrations.CreateModel(
            name='Case',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('entry_date', models.DateField(verbose_name='Дата поступления')),
                ('result_date', models.DateField(blank=True, null=True, verbose_name='Дата решения')),
                ('result_published', models.DateField(blank=True, null=True, verbose_name='Дата публикации решения')),
                ('result_valid', models.DateField(blank=True, null=True, verbose_name='Решение вступило в силу')),
                ('case_number', models.CharField(max_length=50, verbose_name='Номер дела')),
                ('case_uid', models.CharField(blank=True, max_length=50, null=True, verbose_name='ID в sudrf')),
                ('protocol_number', models.CharField(blank=True, max_length=50, null=True, verbose_name='Номер протокола')),
                ('result_type', models.IntegerField(blank=True, choices=[(0, 'Апелляционное ПРОИЗВОДСТВО ПРЕКРАЩЕНО'), (1, 'ВОЗВРАЩЕНО ПРОКУРОРУ'), (2, 'Вынесен ПРИГОВОР'), (3, 'Вынесено другое ПОСТАНОВЛЕНИЕ'), (4, 'Направлено ПО ПОДСУДНОСТИ (подведомственности)'), (5, 'ОСТАВЛЕНО БЕЗ РАССМОТРЕНИЯ в связи с неявкой сторон'), (6, 'Представление (жалоба) ОТОЗВАНЫ'), (7, 'Применены ПРИНУДИТЕЛЬНЫЕ МЕРЫ МЕДИЦИНСКОГО ХАРАКТЕРА'), (8, 'СНЯТО с апелляционного рассмотрения'), (9, 'Уголовное дело ПРЕКРАЩЕНО)'), (10, 'Отмена'), (11, 'Вынесено определение о возвращении протокола об АП и др. материалов дела в орган, долж. лицу ... в случае составления протокола и оформления других материалов дела неправомочными лицами, ...'), (12, 'Вынесено определение о передаче дела по подведомственности (ст 29.9 ч.2 п.2 и ст 29.4 ч.1 п.5)'), (13, 'Вынесено постановление о назначении административного наказания'), (14, 'Вынесено постановление о прекращении производства по делу об адм. правонарушении')], null=True, verbose_name='Решение по делу')),
                ('result_text', models.TextField(blank=True, null=True, verbose_name='Текст решения')),
                ('type', models.IntegerField(choices=[(1, 'Дело об административном правонарушении'), (2, 'Уголовное дело'), (3, 'Производство по материалам')], verbose_name='Тип судопроизводства')),
                ('stage', models.IntegerField(choices=[(1, 'Первая инстанция'), (2, 'Аппеляция'), (3, 'Пересмотр')], verbose_name='Инстанция')),
                ('url', models.URLField(blank=True, null=True, unique=True, verbose_name='URL')),
            ],
            options={
                'verbose_name': 'Дело',
                'verbose_name_plural': 'Дела',
            },
        ),
        migrations.CreateModel(
            name='CaseGroup',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('second_inst', models.BooleanField()),
                ('third_inst', models.BooleanField()),
                ('revision', models.BooleanField()),
            ],
        ),
        migrations.CreateModel(
            name='Defendant',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('name', models.CharField(max_length=50)),
                ('region', models.IntegerField()),
                ('gender', models.IntegerField(blank=True, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='CaseEvent',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('date', models.DateTimeField(blank=True, null=True, verbose_name='Дата')),
                ('type', models.IntegerField(choices=[(0, 'Передача дела судье'), (1, 'Подготовка дела к рассмотрению'), (2, 'Рассмотрение дела по существу'), (3, 'Обращено к исполнению'), (4, 'Вступление постановления (определения) в законную силу'), (5, 'Направленная копия постановления (определения) ВРУЧЕНА'), (6, 'Вручение копии постановления (определения) в соотв. с ч. 2 ст. 29.11 КоАП РФ'), (7, 'Материалы дела сданы в отдел судебного делопроизводства'), (8, 'Направление копии постановления (определения) в соотв. с ч. 2 ст. 29.11 КоАП РФ'), (9, 'Протокол (материалы дела) НЕ БЫЛИ возвращены в ТРЕХДНЕВНЫЙ срок'), (10, 'Направленная копия постановления (определения) ВЕРНУЛАСЬ с отметкой о НЕВОЗМОЖНОСТИ ВРУЧЕНИЯ (п. 29.1 Пост. Пленума ВС от 19.12.2013 № 40)'), (11, 'Производство по делу возобновлено'), (12, 'Регистрация поступившего в суд дела'), (13, 'Передача материалов дела судье'), (14, 'Дело сдано в отдел судебного делопроизводства'), (15, 'Провозглашение приговора'), (16, 'Предварительное слушание'), (17, 'Решение в отношении поступившего уголовного дела'), (18, 'Судебное заседание'), (19, 'Сдача материалов дела в архив'), (20, 'Изготовлено постановление о назначении административного наказания в полном объеме'), (21, 'Изготовлено постановление о прекращении в полном объеме'), (22, 'Окончено производство по исполнению')], verbose_name='Тип')),
                ('result', models.IntegerField(blank=True, choices=[(0, 'Назначено предварительное слушание'), (1, 'Назначено судебное заседание'), (2, 'Рассмотрение отложено'), (3, 'Заседание отложено'), (4, 'Протокол об административном правонарушении (материалы дела) возвращен(ы)  (в пор. ст.29.4 п.4)'), (5, 'Дело возвращено прокурору'), (6, 'Возвращено без рассмотрения'), (7, 'Производство по делу прекращено'), (8, 'Производство по делу приостановлено'), (9, 'Производство прекращено'), (10, 'Вынесено постановление о назначении административного наказания'), (11, 'Вынесено постановление в порядке гл. 51 УПК (о применении ПМ медицинского характера)'), (12, 'Постановление приговора'), (13, 'Провозглашение приговора окончено'), (14, 'Оглашение резолютивной части постановления о назначении административного наказания (изготовление постановления в полном объеме отложено)'), (15, 'Передано по подведомственности'), (16, 'Оглашение резолютивной части постановления о прекращении производства (изготовление постановления в полном объеме отложено)')], null=True, verbose_name='Результат')),
                ('courtroom', models.IntegerField(blank=True, null=True, verbose_name='Зал суда')),
                ('case', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='cases.Case')),
            ],
            options={
                'verbose_name': 'Событие в деле',
                'verbose_name_plural': 'События в деле',
            },
        ),
        migrations.CreateModel(
            name='CaseDefense',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('advocate', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='cases.Advocate', verbose_name='Адвокат')),
                ('case', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='cases.Case')),
                ('codex_articles', models.ManyToManyField(to='codex.CodexArticle', verbose_name='Статьи')),
                ('defendant', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='cases.Defendant', verbose_name='Ответчик')),
            ],
            options={
                'verbose_name': 'Ответчик',
                'verbose_name_plural': 'Ответчики',
            },
        ),
        migrations.AddField(
            model_name='case',
            name='advocates',
            field=models.ManyToManyField(through='cases.CaseDefense', to='cases.Advocate'),
        ),
        migrations.AddField(
            model_name='case',
            name='codex_articles',
            field=models.ManyToManyField(to='codex.CodexArticle', verbose_name='Статьи'),
        ),
        migrations.AddField(
            model_name='case',
            name='court',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='courts.Court', verbose_name='Cуд'),
        ),
        migrations.AddField(
            model_name='case',
            name='defendants',
            field=models.ManyToManyField(through='cases.CaseDefense', to='cases.Defendant'),
        ),
        migrations.AddField(
            model_name='case',
            name='group',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='cases.CaseGroup'),
        ),
        migrations.AddField(
            model_name='case',
            name='judge',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='courts.Judge', verbose_name='Судья'),
        ),
    ]
