# Generated by Django 2.2 on 2019-04-24 13:36

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('cases', '0002_auto_20190420_0750'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='casedefense',
            options={'verbose_name': 'Ответчик в деле', 'verbose_name_plural': 'Ответчики в делах'},
        ),
        migrations.AlterModelOptions(
            name='defendant',
            options={'verbose_name': 'Ответчик', 'verbose_name_plural': 'Ответчики'},
        ),
        migrations.AlterUniqueTogether(
            name='defendant',
            unique_together={('name', 'region')},
        ),
    ]
