# Generated by Django 2.2 on 2019-05-15 09:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cases', '0006_linkedcasesproxy'),
    ]

    operations = [
        migrations.AddField(
            model_name='defendant',
            name='name_normalized',
            field=models.CharField(blank=True, db_index=True, max_length=150, null=True),
        ),
        migrations.AlterField(
            model_name='defendant',
            name='name',
            field=models.CharField(db_index=True, max_length=150),
        ),
    ]
