# Generated by Django 2.2.7 on 2019-12-05 17:23

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('cases', '0014_auto_20191105_1251'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='caseevent',
            options={'ordering': ['date'], 'verbose_name': 'Событие в деле', 'verbose_name_plural': 'События в деле'},
        ),
        migrations.AlterModelOptions(
            name='koapcase',
            options={'ordering': ['-entry_date'], 'verbose_name': 'Дело (КОАП)', 'verbose_name_plural': 'Дела (КОАП)'},
        ),
        migrations.AlterModelOptions(
            name='ukcase',
            options={'ordering': ['-entry_date'], 'verbose_name': 'Дело (УК)', 'verbose_name_plural': 'Дела (УК)'},
        ),
        migrations.AddField(
            model_name='case',
            name='koap_detention_days',
            field=models.IntegerField(blank=True, null=True, verbose_name='Арест (дни)'),
        ),
        migrations.AddField(
            model_name='case',
            name='koap_money_sum',
            field=models.IntegerField(blank=True, null=True, verbose_name='Штраф'),
        ),
        migrations.AddField(
            model_name='case',
            name='koap_public_work_hours',
            field=models.IntegerField(blank=True, null=True, verbose_name='Общественные работы (часы)'),
        ),
        migrations.AlterField(
            model_name='case',
            name='codex_articles',
            field=models.ManyToManyField(related_name='cases', to='codex.CodexArticle', verbose_name='Статьи'),
        ),
        migrations.AlterField(
            model_name='caseevent',
            name='case',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='events', to='cases.Case'),
        ),
    ]
