# Generated by Django 2.2.8 on 2019-12-09 17:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cases', '0015_auto_20191205_1723'),
    ]

    operations = [
        migrations.AlterField(
            model_name='case',
            name='linked_cases',
            field=models.ManyToManyField(blank=True, null=True, related_name='_case_linked_cases_+', to='cases.Case'),
        ),
    ]
