#Generated by Django 2.2.8 on 2019-12-09 19:08

import django.contrib.postgres.indexes
from django.db import migrations
from django.contrib.postgres.operations import BtreeGinExtension

class Migration(migrations.Migration):

    dependencies = [
        ('cases', '0016_auto_20191209_1701'),
    ]

    operations = [
        BtreeGinExtension(),
    ]

