# Generated by Django 2.2.8 on 2019-12-09 20:00

import django.contrib.postgres.indexes
import django.contrib.postgres.search
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('cases', '0017_gin'),
    ]

    operations = [
        migrations.AddField(
            model_name='case',
            name='text_search',
            field=django.contrib.postgres.search.SearchVectorField(null=True),
        ),
        migrations.AddIndex(
            model_name='case',
            index=django.contrib.postgres.indexes.GinIndex(fields=['text_search'], name='cases_case_text_se_e7ded9_gin'),
        ),
    ]
