# Generated by Django 2.2.8 on 2019-12-27 13:03

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('cases', '0019_trigger'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='case',
            name='koap_detention_days',
        ),
        migrations.RemoveField(
            model_name='case',
            name='koap_money_sum',
        ),
        migrations.RemoveField(
            model_name='case',
            name='koap_public_work_hours',
        ),
        migrations.CreateModel(
            name='CasePenalty',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('type', models.CharField(blank=True, choices=[('fine', 'Штраф'), ('works', 'Обязательные работы'), ('arrest_days', 'Арест (в сутках)'), ('term_years', 'Срок (в годах)'), ('other', 'Другое')], max_length=10, null=True)),
                ('num', models.IntegerField(blank=True, null=True)),
                ('is_hidden', models.BooleanField()),
                ('case', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='penalties', to='cases.Case')),
                ('defendant', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='cases.Defendant')),
            ],
            options={
                'verbose_name': 'Наказание',
                'verbose_name_plural': 'Наказания',
                'unique_together': {('case', 'defendant')},
            },
        ),
    ]
