# Generated by Django 2.2.8 on 2020-01-09 14:52

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('cases', '0020_auto_20191227_1303'),
    ]

    operations = [
        migrations.AlterField(
            model_name='casepenalty',
            name='defendant',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='cases.Defendant'),
        ),
        migrations.AlterField(
            model_name='casepenalty',
            name='type',
            field=models.CharField(blank=True, choices=[('fine', 'Штраф'), ('works', 'Обязательные работы'), ('arrest', 'Арест'), ('term', 'Срок'), ('other', 'Другое')], max_length=10, null=True),
        ),
    ]
