# Generated by Django 2.2.8 on 2020-01-21 16:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cases', '0021_auto_20200109_1452'),
    ]

    operations = [
        migrations.AlterField(
            model_name='case',
            name='stage',
            field=models.IntegerField(choices=[(1, 'Первая инстанция'), (2, 'Апелляция/первый пересмотр'), (3, 'Новое рассмотрение в первой инстанции')], verbose_name='Инстанция'),
        ),
    ]
