# Generated by Django 2.2.8 on 2020-04-09 18:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cases', '0022_auto_20200121_1627'),
    ]

    operations = [
        migrations.AlterField(
            model_name='case',
            name='entry_date',
            field=models.DateField(verbose_name='Дата поступления'),
        ),
        migrations.AlterField(
            model_name='casepenalty',
            name='type',
            field=models.CharField(blank=True, choices=[('fine', 'Штраф'), ('works', 'Обязательные работы'), ('arrest', 'Арест'), ('term', 'Срок'), ('other', 'Другое'), ('no_data', 'Нет данных'), ('error', 'Ошибка')], db_index=True, max_length=10, null=True),
        ),
        migrations.AddIndex(
            model_name='case',
            index=models.Index(fields=['-entry_date', '-result_date', 'result_type', 'appeal_result'], name='cases_case_entry_d_cdfa40_idx'),
        ),
    ]
