# Generated by Django 2.2.8 on 2020-05-21 17:14

from django.conf import settings
import django.contrib.postgres.fields.jsonb
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('presets', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='filterpreset',
            old_name='filters',
            new_name='get_params',
        ),
        migrations.AddField(
            model_name='filterpreset',
            name='human_readable',
            field=django.contrib.postgres.fields.jsonb.JSONField(null=True),
        ),
        migrations.AlterField(
            model_name='filterpreset',
            name='category',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='presets', to='presets.FilterPresetCategory'),
        ),
        migrations.AlterField(
            model_name='filterpreset',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='presets', to=settings.AUTH_USER_MODEL),
        ),
    ]
